Kendall tests branch
rfccambridge/robocup-software pull request #5
Opened 2020-05-27 23:28 UTC by kendallzhu

wrote tests for robot_commands

2020-05-31 18:48 UTC, eda214 requested changes
.emacs-buffers should be removed

2020-05-31 18:52 UTC, eda214 commented on comms/tests/test_robot_commands.py
> +def test_set_waypoints():
Document what cases these functions are testing and what is required to pass

2020-05-31 20:09 UTC, wfus commented
@kendallzhu

2020-05-31 20:11 UTC, wfus requested changes

2020-05-31 20:11 UTC, wfus commented on comms/tests/test_robot_commands.py
> +
Need two lines between functions (Linting will be added soon)

2020-05-31 20:11 UTC, wfus commented on comms/tests/test_robot_commands.py
> +
again, two lines between funcs

2020-06-13 19:45 UTC, eda214 approved these changes
Documentation is good now, linting fixes may still be necessary

2020-06-14 20:33 UTC, wfus commented
@kendallzhu  plz merge in master so linting gets checked and it's mergable

2020-06-14 20:33 UTC, wfus reviewed
Needs to merge in master and fix linting

2020-06-18 02:10 UTC, eda214 commented
This looks good to me now! Will let @wfus confirm this time just to make sure I'm not missing anything.

2020-06-18 02:15 UTC, wfus commented
lgtm

2020-06-18 02:15 UTC, wfus approved these changes

2020-06-18 02:33 UTC, merged